services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    ports:
      - '5432:5432'
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api_gateway1:
    build:
      context: ./api-gateway
    container_name: api_gateway1
    ports:
      - "3001:3000"
    depends_on:
      - kafka

  api_gateway2:
    build:
      context: ./api-gateway
    container_name: api_gateway2
    ports:
      - "3002:3000"
    depends_on:
      - kafka

  transaction_service:
    build:
      context: ./transaction-service
    container_name: transaction_service
    depends_on:
      - kafka
      - postgres
      - redis
  
  anti_fraud_service:
    build:
      context: ./anti-fraud-service
    container_name: anti_fraud_service
    depends_on:
      - kafka
      - transaction_service

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_gateway1
      - api_gateway2
